name: C/C++ tests


on: 
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: chmod +x comp-test.sh &&  if ./comp-test.sh ; then exit 1; else exit 0; fi



